import Providers from "@/provider/Providers";
import ThemeProvider from "@/theme/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBarLayout from "./component/sidbar/SideBarLayout";
import "./css/globals.css";
import "./css/tailwind.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Insight Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>


        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <SideBarLayout>{children}</SideBarLayout>
          </Providers>
        </ThemeProvider>
                </AntdRegistry>
      </body>
    </html>
  );
}
